### ISSUE TITLE
Missing elements

### ISSUE THREAD

**Issue by yabab-dev** [marekbrainhub/vue-developer-roadmap#1]
Hi !

Here is a list of some missing stuff:

**E2E tesing**
- Cypress: http://cypress.io
- TestCafe: https://devexpress.github.io/testcafe/

**Routing**
- Vue Auto Routing: https://github.com/ktsn/vue-auto-routing

**SSR**
- Ream: https://ream.js.org/
- VueNeue: https://vueneue.github.io/docs/

**Static generator**
- Nuxt
- Saber.js: https://github.com/egoist/saber.js/
- VueNeue: https://vueneue.github.io/docs/

**Desktop**
- Vuido: https://vuido.mimec.org/
- NW.js: https://nwjs.io/

**Mobile**
- NativeScript Vue: https://nativescript-vue.org/
- Weex: https://weex.incubator.apache.org/

**Comment by marekbrainhub** [comment]
Hey, some of these were added recently. Thank you for your suggestions!
